packages:
  - 'packages/docs'
  - 'packages/stats-generator'
  - 'packages/cwv-stats'

allowBuilds:
  esbuild: true
  sharp: true
  workerd: true

minimumReleaseAgeExclude:
  - baseline-detector@0.3.1

peerDependencyRules:
  allowedVersions:
    'esbuild-plugin-browserslist>esbuild': '0.28'
